# Generated by Django 2.0.1 on 2018-01-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_traveloptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveloptions',
            name='place',
        ),
        migrations.DeleteModel(
            name='TravelOptions',
        ),
    ]
