# Generated by Django 2.0.1 on 2018-01-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
