# Generated by Django 2.0.1 on 2018-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20180109_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.FileField(default='Please upload an image', upload_to=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='info',
            field=models.TextField(default='This is a beautiful place', max_length=1000),
        ),
    ]
